/**
 * Auto-generated API operations from OpenAPI spec.
 *
 * This file is automatically generated by chowbea-axios CLI.
 * DO NOT EDIT MANUALLY - your changes will be overwritten.
 *
 * Total operations: 2
 */

/* ~ =================================== ~ */
/* -- This file provides semantic operation-based API functions -- */
/* -- Use apiClient.op.operationName() instead of raw paths -- */
/* ~ =================================== ~ */

import type { AxiosRequestConfig } from "axios"
import type { Result } from "../api.error"
import type {
  Compress_pdf_compress_postBody,
  Health_health_getResponse,
} from "./api.contracts"

/* ~ =================================== ~ */
/* -- Type Helpers -- */
/* ~ =================================== ~ */

/**
 * Axios request config with typed query parameters for operations that accept them.
 * The type parameter Q is the operation-specific QueryParams contract from api.contracts.
 *
 * Note: an earlier version of this file emitted a MapFormDataTypes
 * helper that re-typed multipart-body string fields as File or Blob
 * based on substring matching of field names. That mis-typed
 * legitimate string fields like "profile" and "filename". Removed in
 * favor of spec-driven binary detection: the contracts file already
 * emits File or Blob for format binary fields. Issue #22.
 */
type RequestConfig<Q> = Omit<AxiosRequestConfig, "params"> & {
  params?: Q
}

/**
 * Structural type for the runtime HTTP client that `createOperations` wraps.
 *
 * Defined locally (rather than imported from `../api.client`) to avoid a
 * circular type-only import: `api.client.ts` imports `createOperations`
 * from this file, so the dependency arrow points one way.
 *
 * Parameter types are intentionally permissive (`any` / `any[]`) because
 * the real runtime client in `api.client.ts` declares its methods generic
 * over the OpenAPI `paths` keyset (e.g. `get<P extends Paths>(url: P, ...)`),
 * which is strictly narrower than this structural shape. Loosening here is
 * what allows the typed runtime client to be assignable to `ApiClient`.
 * The wrapping operation functions declare their own concrete return types
 * (e.g. `Promise<Result<GetUserResponse>>`), so the `any` here does not
 * leak into the public surface of `createOperations`'s return value.
 */
interface ApiClient {
  get: (path: any, ...rest: any[]) => Promise<Result<any>>
  post: (path: any, ...rest: any[]) => Promise<Result<any>>
  put: (path: any, ...rest: any[]) => Promise<Result<any>>
  delete: (path: any, ...rest: any[]) => Promise<Result<any>>
  patch: (path: any, ...rest: any[]) => Promise<Result<any>>
  options: (path: any, ...rest: any[]) => Promise<Result<any>>
  head: (path: any, ...rest: any[]) => Promise<Result<any>>
  trace: (path: any, ...rest: any[]) => Promise<Result<any>>
}

/* ~ =================================== ~ */
/* -- Generated Operations -- */
/* ~ =================================== ~ */

/**
 * Collection of all API operations extracted from the OpenAPI spec.
 * Each operation is a typed function that wraps the underlying apiClient methods.
 *
 * @example
 * ```typescript
 * // Using operation-based API
 * await apiClient.op.getUserById({ id: "123" })
 *
 * // With query parameters
 * await apiClient.op.listUsers({ params: { limit: 10, offset: 0 } })
 *
 * // With request body
 * await apiClient.op.createUser({ name: "John", email: "john@example.com" })
 * ```
 */
export const createOperations = (apiClient: ApiClient) => ({
  /**
   * Compress one or more PDF files
   * Compress the uploaded PDFs and stream back the result.

A single file is returned as a PDF; multiple files are returned as a ZIP archive.
Aggregate size stats are exposed via response headers so the UI can show savings.
   * 
   * @operationId compress_pdf_compress_post
   * @method POST
   * @path /pdf/compress
   */
  compress_pdf_compress_post: (data: Compress_pdf_compress_postBody, config?: AxiosRequestConfig): Promise<Result<unknown>> => apiClient.post("/pdf/compress", data, config),

  /**
   * Liveness check
   * Return a simple status payload used by load balancers and uptime checks.
   * 
   * @operationId health_health_get
   * @method GET
   * @path /health
   */
  health_health_get: (config?: AxiosRequestConfig): Promise<Result<Health_health_getResponse>> => apiClient.get("/health", config),
}) as const

/**
 * Type representing all available API operations.
 * This type is inferred from the createOperations return value for proper TypeScript support.
 */
export type ApiOperations = ReturnType<typeof createOperations>
