/**
 * Concrete type contracts extracted from OpenAPI spec.
 *
 * Auto-generated by chowbea-axios CLI.
 * DO NOT EDIT MANUALLY - changes will be overwritten.
 *
 * Every type is fully expanded inline — no indirection, no generic references.
 * Cmd+click any type to see its full structure right here.
 */

/* ~ =================================== ~ */
/* -- Schema Models -- */
/* ~ =================================== ~ */

/**
 * Schema: Body_compress_pdf_compress_post
 */
export interface Body_compress_pdf_compress_post {
	/** One or more PDF files to compress. */
	files: (File | Blob)[];
	/** Compression preset; 'screen' is smallest, 'prepress' is highest quality. */
	quality?: "screen" | "ebook" | "printer" | "prepress";
}

/**
  * Quality presets that map directly to Ghostscript's -dPDFSETTINGS values.

Lower quality means smaller files: `screen` is the most aggressive,
`prepress` preserves the most detail.
 * Schema: CompressionQuality
 */
export type CompressionQuality = "screen" | "ebook" | "printer" | "prepress";

/**
 * Schema: HTTPValidationError
 */
export interface HTTPValidationError {
	detail?: ({
		loc: (string | number)[];
		msg: string;
		type: string;
	})[];
}

/**
 * Schema: ValidationError
 */
export interface ValidationError {
	loc: (string | number)[];
	msg: string;
	type: string;
}

/* ~ =================================== ~ */
/* -- Operation Responses -- */
/* ~ =================================== ~ */

/** Response: POST /pdf/compress (422 - Validation Error) */
export type Compress_pdf_compress_postResponse422 = {
	detail?: ({
		loc: (string | number)[];
		msg: string;
		type: string;
	})[];
};

/** Response: GET /health (200 - Successful Response) */
export type Health_health_getResponse200 = Record<string, string>;

/** Response: GET /health (happy path) */
export type Health_health_getResponse = Health_health_getResponse200;

/* ~ =================================== ~ */
/* -- Operation Request Bodies -- */
/* ~ =================================== ~ */

/** Request body: POST /pdf/compress */
export type Compress_pdf_compress_postBody = {
	 /** One or more PDF files to compress. */
	files: (File | Blob)[];
	 /** Compression preset; 'screen' is smallest, 'prepress' is highest quality. */
	quality?: "screen" | "ebook" | "printer" | "prepress";
};
