/**
 * Auto-generated API operations from OpenAPI spec.
 *
 * This file is automatically generated by chowbea-axios CLI.
 * DO NOT EDIT MANUALLY - your changes will be overwritten.
 *
 * Total operations: 8
 */

/* ~ =================================== ~ */
/* -- This file provides semantic operation-based API functions -- */
/* -- Use apiClient.op.operationName() instead of raw paths -- */
/* ~ =================================== ~ */

import type { AxiosRequestConfig } from "axios"
import type { Result } from "../api.error"
import type {
  Compress_pdf_compress_postBody,
  Compress_pdf_compress_postResponse,
  Health_health_getResponse,
  Job_download_jobs__job_id__download_getPathParams,
  Job_download_jobs__job_id__download_getResponse,
  Job_status_jobs__job_id__getPathParams,
  Job_status_jobs__job_id__getResponse,
  Lock_pdf_lock_postBody,
  Lock_pdf_lock_postResponse,
  Merge_pdf_merge_postBody,
  Merge_pdf_merge_postResponse,
  Queue_board_queue_getResponse,
  Unlock_pdf_unlock_postBody,
  Unlock_pdf_unlock_postResponse,
} from "./api.contracts"

/* ~ =================================== ~ */
/* -- Type Helpers -- */
/* ~ =================================== ~ */

/**
 * Axios request config with typed query parameters for operations that accept them.
 * The type parameter Q is the operation-specific QueryParams contract from api.contracts.
 *
 * Note: an earlier version of this file emitted a MapFormDataTypes
 * helper that re-typed multipart-body string fields as File or Blob
 * based on substring matching of field names. That mis-typed
 * legitimate string fields like "profile" and "filename". Removed in
 * favor of spec-driven binary detection: the contracts file already
 * emits File or Blob for format binary fields. Issue #22.
 */
type RequestConfig<Q> = Omit<AxiosRequestConfig, "params"> & {
  params?: Q
}

/**
 * Structural type for the runtime HTTP client that `createOperations` wraps.
 *
 * Defined locally (rather than imported from `../api.client`) to avoid a
 * circular type-only import: `api.client.ts` imports `createOperations`
 * from this file, so the dependency arrow points one way.
 *
 * Parameter types are intentionally permissive (`any` / `any[]`) because
 * the real runtime client in `api.client.ts` declares its methods generic
 * over the OpenAPI `paths` keyset (e.g. `get<P extends Paths>(url: P, ...)`),
 * which is strictly narrower than this structural shape. Loosening here is
 * what allows the typed runtime client to be assignable to `ApiClient`.
 * The wrapping operation functions declare their own concrete return types
 * (e.g. `Promise<Result<GetUserResponse>>`), so the `any` here does not
 * leak into the public surface of `createOperations`'s return value.
 */
interface ApiClient {
  get: (path: any, ...rest: any[]) => Promise<Result<any>>
  post: (path: any, ...rest: any[]) => Promise<Result<any>>
  put: (path: any, ...rest: any[]) => Promise<Result<any>>
  delete: (path: any, ...rest: any[]) => Promise<Result<any>>
  patch: (path: any, ...rest: any[]) => Promise<Result<any>>
  options: (path: any, ...rest: any[]) => Promise<Result<any>>
  head: (path: any, ...rest: any[]) => Promise<Result<any>>
  trace: (path: any, ...rest: any[]) => Promise<Result<any>>
}

/* ~ =================================== ~ */
/* -- Generated Operations -- */
/* ~ =================================== ~ */

/**
 * Collection of all API operations extracted from the OpenAPI spec.
 * Each operation is a typed function that wraps the underlying apiClient methods.
 *
 * @example
 * ```typescript
 * // Using operation-based API
 * await apiClient.op.getUserById({ id: "123" })
 *
 * // With query parameters
 * await apiClient.op.listUsers({ params: { limit: 10, offset: 0 } })
 *
 * // With request body
 * await apiClient.op.createUser({ name: "John", email: "john@example.com" })
 * ```
 */
export const createOperations = (apiClient: ApiClient) => ({
  /**
   * Queue one or more PDF files for compression
   * Validate and store the uploads, then queue a compression job.
   * 
   * @operationId compress_pdf_compress_post
   * @method POST
   * @path /pdf/compress
   */
  compress_pdf_compress_post: (data: Compress_pdf_compress_postBody, config?: AxiosRequestConfig): Promise<Result<Compress_pdf_compress_postResponse>> => apiClient.post("/pdf/compress", data, config),

  /**
   * Queue a password removal job for a PDF file
   * Validate and store the upload, then queue an unlock job.
   * 
   * @operationId unlock_pdf_unlock_post
   * @method POST
   * @path /pdf/unlock
   */
  unlock_pdf_unlock_post: (data: Unlock_pdf_unlock_postBody, config?: AxiosRequestConfig): Promise<Result<Unlock_pdf_unlock_postResponse>> => apiClient.post("/pdf/unlock", data, config),

  /**
   * Queue a password protection job for a PDF file
   * Validate and store the upload, then queue a lock job.
   * 
   * @operationId lock_pdf_lock_post
   * @method POST
   * @path /pdf/lock
   */
  lock_pdf_lock_post: (data: Lock_pdf_lock_postBody, config?: AxiosRequestConfig): Promise<Result<Lock_pdf_lock_postResponse>> => apiClient.post("/pdf/lock", data, config),

  /**
   * Queue a merge of two or more PDF files
   * Validate and store the uploads, then queue a merge job.
   * 
   * @operationId merge_pdf_merge_post
   * @method POST
   * @path /pdf/merge
   */
  merge_pdf_merge_post: (data: Merge_pdf_merge_postBody, config?: AxiosRequestConfig): Promise<Result<Merge_pdf_merge_postResponse>> => apiClient.post("/pdf/merge", data, config),

  /**
   * Poll a job's status
   * 
   * @operationId job_status_jobs__job_id__get
   * @method GET
   * @path /jobs/{job_id}
   * @remarks Path parameter values are URL-encoded by the underlying HTTP layer (axios) before the request is dispatched. Callers may pass raw values.
   */
  job_status_jobs__job_id__get: (pathParams: Job_status_jobs__job_id__getPathParams, config?: AxiosRequestConfig): Promise<Result<Job_status_jobs__job_id__getResponse>> => apiClient.get("/jobs/{job_id}", pathParams, config),

  /**
   * Download a finished job's result
   * 
   * @operationId job_download_jobs__job_id__download_get
   * @method GET
   * @path /jobs/{job_id}/download
   * @remarks Path parameter values are URL-encoded by the underlying HTTP layer (axios) before the request is dispatched. Callers may pass raw values.
   */
  job_download_jobs__job_id__download_get: (pathParams: Job_download_jobs__job_id__download_getPathParams, config?: AxiosRequestConfig): Promise<Result<Job_download_jobs__job_id__download_getResponse>> => apiClient.get("/jobs/{job_id}/download", pathParams, config),

  /**
   * Public queue board
   * 
   * @operationId queue_board_queue_get
   * @method GET
   * @path /queue
   */
  queue_board_queue_get: (config?: AxiosRequestConfig): Promise<Result<Queue_board_queue_getResponse>> => apiClient.get("/queue", config),

  /**
   * Liveness check
   * Return a status payload used by load balancers, uptime checks, and
bug reports (the commit identifies the running deploy).
   * 
   * @operationId health_health_get
   * @method GET
   * @path /health
   */
  health_health_get: (config?: AxiosRequestConfig): Promise<Result<Health_health_getResponse>> => apiClient.get("/health", config),
}) as const

/**
 * Type representing all available API operations.
 * This type is inferred from the createOperations return value for proper TypeScript support.
 */
export type ApiOperations = ReturnType<typeof createOperations>
